[tool.black]
line-length = 79
target-version = ['py312']
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov=app --cov-report=html --cov-report=xml --cov-report=term-missing"
testpaths = "tests"