"""change role type

Revision ID: 2029e1e58061
Revises: feb25c428031
Create Date: 2025-08-07 18:13:21.936872

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2029e1e58061'
down_revision: Union[str, Sequence[str], None] = 'feb25c428031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.create_unique_constraint("uq_role_role_type", ['role_type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
