"""creating order and order_detail tables

Revision ID: feb25c428031
Revises: 851ee1fdaca9
Create Date: 2025-08-06 11:00:24.640121

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feb25c428031"
down_revision: Union[str, Sequence[str], None] = "851ee1fdaca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PREPARING",
                "READY",
                "SERVED",
                "CANCELLED",
                "PAID",
                name="order_status",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orderdetail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "comment", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PREPARING",
                "READY",
                "SERVED",
                "CANCELLED",
                name="order_detail_status",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["menu.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderdetail")
    op.drop_table("order")
    # ### end Alembic commands ###
