name: Project CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Continue the other matrix'jobs even if one fails.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: | # allows to run several commands
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest_reports
          path: pytest_report.xml
        if: always() # this step is always executed to make sure reports can be uploaded.